create table "users"(
	"user_id" serial primary key,
	"username" varchar
);

create table "users2"(
	"user_id" integer generated by default as identity primary key,
	"username" varchar
);

-- user can't insert manual id
create table "users3"(
	"user_id" integer generated always as identity primary key,
	"username" varchar
);

create table "users4"(
	"user_id" integer generated always as identity (start with 100 increment by 2) primary key,
	"username" varchar
);